# Generated by Django 2.1.1 on 2018-09-15 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_sources', to='bio.Gene')),
            ],
        ),
    ]
