# Generated by Django 2.1.1 on 2018-09-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0003_auto_20180918_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='detail',
            field=models.TextField(default='', max_length=500),
        ),
    ]
